-- Baseline schema, mirroring the tables Hibernate's ddl-auto=update previously
-- generated from the JPA entities in com.example.booking_service.model.
-- From here on, schema changes go through new Vn__*.sql files instead of
-- auto-DDL.

CREATE TABLE trains (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_number        INTEGER NOT NULL UNIQUE,
    train_name          VARCHAR(255) NOT NULL,
    source              VARCHAR(255) NOT NULL,
    destination         VARCHAR(255) NOT NULL,
    departure_time       TIMESTAMP NOT NULL,
    arrival_time        TIMESTAMP NOT NULL,
    duration_in_minutes  INTEGER NOT NULL,
    distance_km         DOUBLE PRECISION NOT NULL,
    total_seats         INTEGER NOT NULL,
    available_seats      INTEGER NOT NULL,
    fare                NUMERIC(10, 2) NOT NULL,
    train_type          VARCHAR(30) NOT NULL,
    status              VARCHAR(30) NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL
);

CREATE INDEX idx_trains_status ON trains (status);
CREATE INDEX idx_trains_source_destination ON trains (source, destination);

CREATE TABLE train_schedules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_id         BIGINT NOT NULL,
    journey_date      DATE NOT NULL,
    total_seats      INTEGER NOT NULL,
    available_seats   INTEGER NOT NULL,
    rac_count        INTEGER NOT NULL DEFAULT 0,
    waitlist_count    INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    CONSTRAINT uk_train_schedules_train_journey_date UNIQUE (train_id, journey_date)
);

CREATE TABLE bookings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference     VARCHAR(40),
    pnr                  VARCHAR(15) NOT NULL UNIQUE,
    user_id              BIGINT NOT NULL,
    user_email            VARCHAR(255) NOT NULL,
    passenger_name        VARCHAR(255) NOT NULL,
    age                  INTEGER NOT NULL,
    gender               VARCHAR(20) NOT NULL,
    seat_number           VARCHAR(255),
    train_id             BIGINT NOT NULL,
    train_number          INTEGER NOT NULL,
    train_name            VARCHAR(255) NOT NULL,
    source               VARCHAR(255) NOT NULL,
    destination          VARCHAR(255) NOT NULL,
    train_class           VARCHAR(20) NOT NULL,
    quota                VARCHAR(20) NOT NULL,
    journey_date          DATE NOT NULL,
    fare                 NUMERIC(10, 2) NOT NULL,
    booking_status        VARCHAR(30) NOT NULL,
    ticket_pdf_sent_at      TIMESTAMP,
    hold_expires_at        TIMESTAMP,
    booking_time          TIMESTAMP NOT NULL,
    created_at           TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP NOT NULL
);

CREATE INDEX idx_bookings_user_id ON bookings (user_id);
CREATE INDEX idx_bookings_user_email ON bookings (user_email);
CREATE INDEX idx_bookings_train_journey_date ON bookings (train_id, journey_date);
CREATE INDEX idx_bookings_journey_date ON bookings (journey_date);
CREATE INDEX idx_bookings_status_hold_expiry ON bookings (booking_status, hold_expires_at);

CREATE TABLE passengers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT NOT NULL,
    passenger_name    VARCHAR(255) NOT NULL,
    age             INTEGER NOT NULL,
    gender          VARCHAR(20) NOT NULL,
    seat_number      VARCHAR(10),
    created_at      TIMESTAMP NOT NULL
);

CREATE INDEX idx_passengers_booking_id ON passengers (booking_id);

CREATE TABLE notification_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT NOT NULL,
    pnr             VARCHAR(15) NOT NULL,
    event_type       VARCHAR(50) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    status          VARCHAR(30) NOT NULL,
    failure_reason    TEXT,
    retry_count      INTEGER NOT NULL DEFAULT 0,
    email_sent_at     TIMESTAMP,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL
);

CREATE TABLE stations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_code   VARCHAR(255) NOT NULL UNIQUE,
    station_name   VARCHAR(255) NOT NULL,
    aliases       VARCHAR(500),
    city          VARCHAR(100),
    created_at    TIMESTAMP NOT NULL
);
